<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Vortex_PT-BR_Launcher</AssemblyName>
    <RootNamespace>VortexPtBrLauncher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>vortex-ptbr.ico</ApplicationIcon>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
